### PR TITLE
Update extension to work with GNOME 3.36

### PR DESCRIPTION
**Pull request by coldtobi**
NOTE: In GNOME 3.36 the possibilty to switch behaviour on Alt has been removed.
Therefore the behaviour of this extension changes that it is no longer possible
to switch between "Suspend" and "Power Off" by holding down the Alt key.

Instead, you can now configure to show either "Suspend" or "Power Off".

NOTE2: Gnome 3.36 comes with built in support for a Suspend and Power-Off Menue,
making this extension somehow obsolete. Though this extension exposed the menue
"with one click less".

This should tackle isse #53.

### CODE REVIEW

**Comment by coldtobi** [comment]
PS:  The PR is _NOT_ backward compatible to older GNOMEs

**Review by ConeyIsland — CHANGES_REQUESTED** [review]
No, it's not the solution. It should be 4 beautiful round buttons like on extension's page screenshot at gnome store - "log out", "suspend", "restart" and "power off". Default gnome links should be disabled at the same time. 
Look at the example of buttons in this extension: https://extensions.gnome.org/extension/1460/vitals/

**Comment by coldtobi** [comment]
> No, it's not the solution. It should be 4 beautiful round buttons like on extension's page screenshot at gnome store - "log out", "suspend", "restart" and "power off". Default gnome links should be disabled at the same time.
> Look at the example of buttons in this extension: https://extensions.gnome.org/extension/1460/vitals/

GNOME 3.36 removed saome important APIs to facilitate this.
But I'm not a JavaScript / Gnome Extensions developer, so I will not dig into this to see if there are other ways because of ENOTIME.

IOW @ConeyIsland Feel free to pick up the issue!

**Comment by coldtobi** [comment]
closing it because frankly, this extension is no longer maintained.

**Pull request closed without merging**
